query Articles {
  articleCollection {
    items {
      title
      slug
      content
      creationTime
      readingTime
      claps
      thumbnail {
        url
      }
      sys {
        id
      }
      author {
        name
        bio
        positionRole
        followers
        profilePicture {
          url
        }
      }
      tag {
        tagName
      }
    }
  }
}
